apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: health_db
    user: health_user
    secureJsonData:
      password: health_pass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
    isDefault: true
    editable: true
